services:
  gameserver:
    image: ghcr.io/toast-ts/farmsim-docker:master
    container_name: fs22-game
    restart: unless-stopped
    environment:
      - VNC_PASSWORD=vnc_pw
      - PUID=1000
      - PGID=1000
      - WEB_USERNAME=admin
      - WEB_PASSWORD=admin_pw
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/fs22/config:/opt/fs22/config
      - /opt/fs22/game:/opt/fs22/game
      - /opt/fs22/dlc:/opt/fs22/dlc
      - /opt/fs22/install:/opt/fs22/install
      - /opt/fs22/logs:/opt/fs22/logs
    ports:
      - 5900:5900/tcp # VNC
      - 8080:8080/tcp # Webinterface
      - 10823:10823/udp # Game
    cap_add:
      - SYS_NICE
