services:
  gameserver:
    image: ghcr.io/toast-ts/farmsim-docker:fs25
    container_name: fs25-server
    restart: unless-stopped
    environment:
      - VNC_PASSWORD=vnc_pw
      - PUID=1000
      - PGID=1000
      - WEB_USERNAME=admin
      - WEB_PASSWORD=admin_pw
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/fs25/docs:/opt/fs25/docs
      - '/opt/fs25/game:/home/nobody/.fs_server/drive_c/Program Files (x86)/Farming Simulator 2025'
      - /opt/fs25/dlc:/opt/fs25/dlc
      - /opt/fs25/install:/opt/fs25/install
      - /opt/fs25/logs:/opt/fs25/logs
    ports:
      - 5900:5900/tcp # VNC
      - 8080:8080/tcp # Webinterface
      - 10823:10823/udp # Game (UDP)
      - 10823:10823/tcp # Game<-->GIANTS (from what I'm told anyway)
    cap_add:
      - SYS_NICE
